### PR TITLE
make this repo compatible with DAPS native assembly support

### PR DESCRIPTION
**Pull request by ghost**
what it says on the tin.

### CODE REVIEW

**Comment by ghost** [comment]
@tomschr ?

**Comment by tomschr** [comment]
Thanks Stefan! :+1:

**Comment by ghost** [comment]
Thank you for merging!

@tomschr Would you mind giving Jana/Tanja/Frank/me access to the repo too? I think it would be nice to be able to update it if need be for additional tests.

**Comment by tomschr** [comment]
@sknorr Of course! My bad. I've added all of you now. Have fun!

**Pull request merged**
